@baseUrl = http://js-post-api.herokuapp.com/api

# students

# @name getAllStudents
GET {{baseUrl}}/students?_page=1&_limit=10&_sort=mark&_order=desc

###

# @name getAllStudentsById
GET {{baseUrl}}/students/u6V7vww

###

# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
  "name": "drogon",
  "age": 26,
  "mark": 9,
  "gender": "male",
  "city": "HN"
}

###

# @name updateStudent
PATCH {{baseUrl}}/students/u6V7vww
Content-Type: application/json

{
  "name": "drooogon"
}

###

# @name removeStudent
DELETE {{baseUrl}}/students/u6V7vww